[project]
name = "mmm-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matthew Reda", email = "m.reda94@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numba>=0.63.1",
    "numpy>=2.3.5",
    "numpyro>=0.19.0",
    "nutpie>=0.16.4",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "pymc>=5.26.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mmm-framework",
]
app = [
    "plotly>=6.5.0",
    "streamlit>=1.52.1",
]

[tool.uv.sources]
mmm-framework = { workspace = true }
